force-app/main/default/objects/Contact/fields/PermanentResidenceLocation__c.field-meta.xml
<CustomField>
    <fullName>PermanentResidenceLocation__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Permanent Residence Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Parent__c.field-meta.xml
<CustomField>
    <fullName>Parent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>SubLocations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/selector/UserSelector.cls
/**
 * @description TODO:DESCRIPTION
 * @author Created by vassil.petkov@next-consult.com on 2024/11/24.
 */

public with sharing class UserSelector implements IUserSelector {
	public static IUserSelector getInstance() {
		return new UserSelector();
	}

	public Set<Id> getCurrentUserLocationIds() {
		Id locationId = [
				SELECT Contact.PermanentResidenceLocation__c
				FROM User
				WHERE Id = :UserInfo.getUserId()
		].Contact.PermanentResidenceLocation__c;
		Set<Id> locationIds = new Set<Id> { locationId };
		while( true ) {
			Id upperLocation = [ SELECT Parent__c FROM Location__c WHERE Id = :locationId ].Parent__c;
			if( String.isBlank( upperLocation ) ) {
				break;
			}
			locationId = upperLocation;
			locationIds.add( locationId );
		}
		return locationIds;
	}

	public Id getCurrentUserAccountId() {
		return [ SELECT AccountId FROM User WHERE Id = :UserInfo.getUserId() ].AccountId;
	}
}