force-app/main/default/objects/Election__c/Election__c.object-meta.xml
<CustomObject>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ElectionVoter__c/ElectionVoter__c.object-meta.xml
<CustomObject>
    <label>Election Voter</label>
    <nameField>
        <label>Election Voter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Election Voters</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ElectionVoter__c/fields/Election__c.field-meta.xml
<CustomField>
    <fullName>Election__c</fullName>
    <label>Election</label>
    <referenceTo>Election__c</referenceTo>
    <relationshipLabel>Election Voters</relationshipLabel>
    <relationshipName>ElectionVoters</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ElectionVoter__c/fields/Voter__c.field-meta.xml
<CustomField>
    <fullName>Voter__c</fullName>
    <label>Voter</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Only a person account can register to vote.</errorMessage>
        <filterItems>
            <field>Account.IsPersonAccount</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Election Voters</relationshipLabel>
    <relationshipName>ElectionVoters</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/selector/ElectionVoterSelector.cls
/**
 * @description TODO:DESCRIPTION
 * @author Created by vassil.petkov@next-consult.com on 2024/11/24.
 */

public with sharing class ElectionVoterSelector implements IElectionVoterSelector {
	public static IElectionVoterSelector getInstance() {
		return new ElectionVoterSelector();
	}

	public List<ElectionVoter__c> getElectionVoterRecord( Id electionId, Id voterId ) {
		return [
				SELECT Id
				FROM ElectionVoter__c
				WHERE Election__c = :electionId
				AND Voter__c = :voterId
		];
	}
}