force-app/main/default/objects/Election__c/Election__c.object-meta.xml
<CustomObject>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Election__c/fields/BackgroundImageUrl__c.field-meta.xml
<CustomField>
    <fullName>BackgroundImageUrl__c</fullName>
    <label>Background Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Election__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Elections</relationshipLabel>
    <relationshipName>Elections</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Election__c/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Election__c/fields/VotingEndDate__c.field-meta.xml
<CustomField>
    <fullName>VotingEndDate__c</fullName>
    <label>Voting End Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Election__c/fields/VotingStartDate__c.field-meta.xml
<CustomField>
    <fullName>VotingStartDate__c</fullName>
    <label>Voting Start Date</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/selector/ElectionSelector.cls
/**
 * @description TODO:DESCRIPTION
 * @author Created by vassil.petkov@next-consult.com on 2024/11/24.
 */

public without sharing class ElectionSelector implements IElectionSelector {
	public static IElectionSelector getInstance() {
		return new ElectionSelector();
	}

	public List<Election__c> getCurrentElections( Set<Id> locationIds ) {
		return [
				SELECT Name,
						ShortDescription__c
				FROM Election__c
				WHERE Published__c = TRUE
				AND VotingStartDate__c <= TODAY
				AND VotingEndDate__c >= TODAY
				AND Location__c IN :locationIds
		];
	}

	public List<Election__c> getUpcomingElections( Set<Id> locationIds ) {
		return [
				SELECT Name,
						ShortDescription__c
				FROM Election__c
				WHERE Published__c = TRUE
				AND VotingEndDate__c < TODAY
				AND Location__c IN :locationIds
		];
	}

	public List<Election__c> getPastElections( Set<Id> locationIds ) {
		return [
				SELECT Name,
						ShortDescription__c
				FROM Election__c
				WHERE Published__c = TRUE
				AND VotingEndDate__c < TODAY
				AND Location__c IN :locationIds
		];
	}

	public Election__c getElectionDetails( Id electionId ) {
		return [
				SELECT
						Name,
						Description__c,
						BackgroundImageUrl__c
				FROM Election__c
		];
	}
}