force-app/main/default/objects/Election__c/Election__c.object-meta.xml
<CustomObject>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Election__c/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/model/ElectionTableModel.cls
/**
 * @description TODO:DESCRIPTION
 * @author Created by vassil.petkov@next-consult.com on 2024/11/24.
 */

public with sharing class ElectionTableModel {
	public ElectionTableModel( Election__c election ) {
		this.electionId = election.Id;
		this.electionName = election.Name;
		this.shortDescription = election.ShortDescription__c;
		this.electionUrl = '/voting/election-overview?electionId=' + election.Id;
	}

	@AuraEnabled
	public Id electionId { get; private set; }
	@AuraEnabled
	public String electionName { get; private set; }
	@AuraEnabled
	public String shortDescription { get; private set; }
	@AuraEnabled
	public String electionUrl { get; private set; }
}