force-app/main/default/objects/Choice__c/Choice__c.object-meta.xml
<CustomObject>
    <label>Choice</label>
    <nameField>
        <label>Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Choice__c/fields/Election__c.field-meta.xml
<CustomField>
    <fullName>Election__c</fullName>
    <label>Election</label>
    <referenceTo>Election__c</referenceTo>
    <relationshipLabel>Choices</relationshipLabel>
    <relationshipName>Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Choice__c/fields/PictureUrl__c.field-meta.xml
<CustomField>
    <fullName>PictureUrl__c</fullName>
    <label>Picture Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Choice__c/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Choice__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ChoiceType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Election__c/Election__c.object-meta.xml
<CustomObject>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Election__c/fields/BackgroundImageUrl__c.field-meta.xml
<CustomField>
    <fullName>BackgroundImageUrl__c</fullName>
    <label>Background Image Url</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Election__c/fields/ShortDescription__c.field-meta.xml
<CustomField>
    <fullName>ShortDescription__c</fullName>
    <label>Short Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/ChoiceType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Person</fullName>
    </customValue>
    <customValue>
        <fullName>Party</fullName>
    </customValue>
    <customValue>
        <fullName>Policy</fullName>
    </customValue>
    <masterLabel>Choice Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/selector/ChoiceSelector.cls
/**
 * @description TODO:DESCRIPTION
 * @author Created by vassil.petkov@next-consult.com on 2024/11/24.
 */

public with sharing class ChoiceSelector implements IChoiceSelector {
	public List<Choice__c> getChoicesForElection( Id electionId ) {
		return [
				SELECT Name,
						ShortDescription__c,
						Type__c
				FROM Choice__c
				WHERE Election__c = :electionId
				ORDER BY Order__c ASC
		];
	}

	public Choice__c getChoiceDetails( Id choiceId ) {
		return [
				SELECT Name,
						ShortDescription__c,
						Description__c,
						PictureUrl__c,
						BackgroundImageUrl__c,
						Type__c
				FROM Choice__c
				WHERE Id = :choiceId
		];
	}
}