force-app/main/default/objects/Choice__c/Choice__c.object-meta.xml
<CustomObject>
    <label>Choice</label>
    <nameField>
        <label>Choice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Choices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Choice__c/fields/Election__c.field-meta.xml
<CustomField>
    <fullName>Election__c</fullName>
    <label>Election</label>
    <referenceTo>Election__c</referenceTo>
    <relationshipLabel>Choices</relationshipLabel>
    <relationshipName>Choices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Election__c/Election__c.object-meta.xml
<CustomObject>
    <label>Election</label>
    <nameField>
        <label>Election Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elections</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/controller/ElectionOverviewController.cls
/**
 * @description TODO:DESCRIPTION
 * @author Created by vassil.petkov@next-consult.com on 2024/11/24.
 */

public with sharing class ElectionOverviewController {
	@AuraEnabled(Cacheable=true)
	public static Election__c getElectionOverviewData( Id electionId ) {
		return ElectionSelector.getInstance().getElectionDetails( electionId );
	}

	@AuraEnabled(Cacheable=true)
	public static List<ChoiceTableModel> getChoices( Id electionId ) {
		List<ChoiceTableModel> choices = new List<ChoiceTableModel>();
		for( Choice__c choice : ChoiceSelector.getInstance().getChoicesForElection( electionId ) ) {
			choices.add( new ChoiceTableModel( choice ) );
		}
		return choices;
	}
}